### ISSUE TITLE
最新版本的修改了前端集成关系，菜单没有实时对应显示，还有tpl和tpl_src用什么工具编译的呢

### ISSUE THREAD

**Issue by leiliang520130** [baijunyao/thinkphp-bjyadmin#16]
最新版本的修改了前端集成关系，菜单没有实时对应显示，还有tpl和tpl_src用什么工具编译的呢，谢谢。

**Comment by baijunyao** [comment]
修改了前端集成关系每太明白；  使用的是 gulp  [thinkphp 整合系列之 gulp 实现前端自动化](https://baijunyao.com/article/103)

**Comment by leiliang520130** [comment]
之前用的是iframe，左边的菜单是不被刷新的，所以是记录状态的，现在这样继承的话，就不能回显

**Comment by baijunyao** [comment]
已修复；多谢反馈；
