### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by Existence01** [baijunyao/thinkphp-bjyadmin#2]
发现一个问题 当后台添加新导航分类时 添加成功 但无法显示出来 然后给新导航添加权限 接着再给管理员添加访问新导航的权限 然后新导航才显示出来 对于权限问题有啥更方便的解决方法

**Comment by baijunyao** [comment]
恩恩；对于这个问题；之前也讨论过；容我抽空寻一个可以偷懒的方式；http://git.oschina.net/shuaibai123/thinkphp-bjyadmin/issues/5
