### ISSUE TITLE
好像出错了第三步确认完出现

### ISSUE THREAD

**Issue by YeChenLiu** [baijunyao/thinkphp-bjyadmin#4]
Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: Cannot modify header information - headers already sent in Unknown on line 0

Warning: Cannot modify header information - headers already sent in D:\phpdemo\thinkphp-bjyadmin-master\Public\install\index.php on line 5

**Comment by baijunyao** [comment]
set 'always_populate_raw_post_data' to '-1' in php.ini
