### ISSUE TITLE
同一个页面放两个上传，第一个上传无效

### ISSUE THREAD

**Issue by j-colter** [baijunyao/thinkphp-bjyadmin#5]
如题，在同一个页面放两个上传，点击第一个上传无反应，点击第二个再点击第一个又可以了

**Comment by baijunyao** [comment]
请问是什么操作系统？浏览器？版本？

**Comment by halay** [comment]
我也遇到过 谷歌浏览器，win7

**Comment by baijunyao** [comment]
我示例页面增加了多个webuploader；依然没测试到这个问题；可以拉取最新代码查看；
