### ISSUE TITLE
mysql连结错误

### ISSUE THREAD

**Issue by lylexist** [baijunyao/thinkphp-bjyadmin#6]
我在安装向导中第3步的时候提示：“bjyadmin unknown mysql server host '127.0.0.1:3306'(2)”，我是单独创建了数据库用户和数据库，并且赋权给用户后将管理信息填进去的。

**Comment by puge2016** [comment]
我也碰到这个问题，直接终端里面导入数据库，配置db.php文件。就行了。

**Comment by baijunyao** [comment]
这种情况一般就是数据库链接失败；实在找不到问题；有个暴力的安装方式；参考文章 [http://baijunyao.com/article/104](http://baijunyao.com/article/104)
